//! Rust port of Airflow Lab's D2Q9 regularized BGK solver.
//! This deliberately retains f64 precision, cell order and equations from simulation.mjs.
//! Shape masks are generated by the original JavaScript solver and copied into WASM.
//! The exported ABI is private to wasm-engine.mjs; no wasm-bindgen dependency required.

const CX: [isize; 9] = [0, 1, 0, -1, 0, 1, -1, -1, 1];
const CY: [isize; 9] = [0, 0, 1, 0, -1, 1, 1, -1, -1];
const WT: [f64; 9] = [4.0/9.0,1.0/9.0,1.0/9.0,1.0/9.0,1.0/9.0,1.0/36.0,1.0/36.0,1.0/36.0,1.0/36.0];
const OP: [usize; 9] = [0,3,4,1,2,7,8,5,6];
const DT: f64 = 0.5;
const OMEGA_SMOOTHING: f64 = 0.98;

pub struct Solver {
    w: usize,
    h: usize,
    n: usize,
    f: Vec<f64>,
    next: Vec<f64>,
    solid: Vec<u8>,
    rho: Vec<f64>,
    ux: Vec<f64>,
    uy: Vec<f64>,
    speed: f64,
    viscosity: f64,
    inlet_speed: f64,
    pub time: usize,
    force_x: f64,
    force_y: f64,
}

impl Solver {
    fn new(w: usize, h: usize, speed: f64, viscosity: f64) -> Option<Self> {
        if !(24..=512).contains(&w) || !(24..=256).contains(&h) ||
            !speed.is_finite() || !(0.0..=0.2).contains(&speed) ||
            !viscosity.is_finite() || !(0.02..=0.15).contains(&viscosity) { return None; }
        let n = w*h;
        Some(Self {
            w, h, n,
            f: vec![0.0; n*9],
            next: vec![0.0; n*9],
            solid: vec![0; n],
            rho: vec![1.0; n],
            ux: vec![0.0; n],
            uy: vec![0.0; n],
            speed, viscosity, inlet_speed: speed,
            time: 0, force_x: 0.0, force_y: 0.0,
        })
    }
    #[inline(always)]
    fn equilibrium_into(target: &mut [f64], n: usize, i: usize, u: f64, v: f64, rho: f64) {
        let u2=u*u+v*v;
        for q in 0..9 {
            let cu=(CX[q] as f64)*u+(CY[q] as f64)*v;
            target[q*n+i]=WT[q]*rho*(1.0+3.0*cu+4.5*cu*cu-1.5*u2);
        }
    }
    fn reset(&mut self) {
        self.inlet_speed=self.speed;
        for i in 0..self.n {
            let vel=if self.solid[i]!=0 {0.0} else {self.speed};
            Self::equilibrium_into(&mut self.f,self.n,i,vel*DT,0.0,1.0);
            self.rho[i]=1.0;self.ux[i]=vel;self.uy[i]=0.0;
        }
        self.next.fill(0.0);
        self.time=0;self.force_x=0.0;self.force_y=0.0;
    }
    fn substep(&mut self) -> bool {
        let w=self.w;let h=self.h;let n=self.n;
        let omega=1.0/(3.0*self.viscosity*DT+0.5);
        self.next.fill(0.0);
        let difference=self.speed-self.inlet_speed;
        self.inlet_speed+=difference.max(-0.00025*DT).min(0.00025*DT);
        let mut fx=0.0;let mut fy=0.0;
        let mut eq=[0.0;9];let mut correction=[0.0;9];
        for y in 0..h {
            for x in 0..w {
                let i=x+y*w;
                if self.solid[i]!=0 {continue;}
                let mut rho=0.0;let mut u=0.0;let mut v=0.0;
                let mut pxx=0.0;let mut pxy=0.0;let mut pyy=0.0;
                for q in 0..9 {
                    let value=self.f[q*n+i];
                    let cx=CX[q] as f64;let cy=CY[q] as f64;
                    rho+=value;u+=value*cx;v+=value*cy;
                    pxx+=value*cx*cx;pxy+=value*cx*cy;pyy+=value*cy*cy;
                }
                if !rho.is_finite() || rho<=0.0 {return false;}
                u/=rho;v/=rho;
                let u2=u*u+v*v;
                pxx-=rho*(u*u+1.0/3.0);
                pxy-=rho*u*v;
                pyy-=rho*(v*v+1.0/3.0);
                let mut limiter: f64=1.0;
                for q in 0..9 {
                    let cx=CX[q] as f64;let cy=CY[q] as f64;
                    let cu=cx*u+cy*v;
                    let equilibrium=WT[q]*rho*(1.0+3.0*cu+4.5*cu*cu-1.5*u2);
                    if equilibrium<=0.0 || !equilibrium.is_finite() {return false;}
                    let reg=4.5*WT[q]*((cx*cx-1.0/3.0)*pxx+2.0*cx*cy*pxy+(cy*cy-1.0/3.0)*pyy);
                    let delta=(1.0-omega)*reg;
                    eq[q]=equilibrium;correction[q]=delta;
                    if delta<0.0 {limiter=limiter.min(0.999*equilibrium/-delta);}
                }
                for q in 0..9 {
                    let post=eq[q]+limiter*correction[q];
                    let xx=x as isize+CX[q];let yy=y as isize+CY[q];
                    if xx<0||xx>=w as isize||yy<0||yy>=h as isize {continue;}
                    let j=xx as usize+(yy as usize)*w;
                    if self.solid[j]!=0 {
                        self.next[OP[q]*n+i]+=post;
                        fx+=2.0*post*(CX[q] as f64);
                        fy+=2.0*post*(CY[q] as f64);
                    }else{
                        self.next[q*n+j]+=post;
                    }
                }
            }
        }
        for y in 0..h {
            Self::equilibrium_into(&mut self.next,n,y*w,self.inlet_speed*DT,0.0,1.0);
            for q in 0..9 {self.next[q*n+y*w+w-1]=self.next[q*n+y*w+w-2];}
        }
        for x in 0..w {
            Self::equilibrium_into(&mut self.next,n,x,self.inlet_speed*DT,0.0,1.0);
            Self::equilibrium_into(&mut self.next,n,x+(h-1)*w,self.inlet_speed*DT,0.0,1.0);
        }
        std::mem::swap(&mut self.f,&mut self.next);
        for i in 0..n {
            if self.solid[i]!=0 {self.rho[i]=1.0;self.ux[i]=0.0;self.uy[i]=0.0;continue;}
            let mut rho=0.0;let mut u=0.0;let mut v=0.0;
            for q in 0..9 {
                let value=self.f[q*n+i];
                rho+=value;u+=value*(CX[q] as f64);v+=value*(CY[q] as f64);
            }
            if !rho.is_finite()||rho<0.2||rho>3.0||!u.is_finite()||!v.is_finite(){return false;}
            self.rho[i]=rho;self.ux[i]=u/rho/DT;self.uy[i]=v/rho/DT;
        }
        let smoothing=1.0-OMEGA_SMOOTHING.powf(DT);
        let force_scale=1.0/(DT*DT);
        self.force_x=(1.0-smoothing)*self.force_x+smoothing*fx*force_scale;
        self.force_y=(1.0-smoothing)*self.force_y+smoothing*fy*force_scale;
        true
    }
    fn step(&mut self)->bool {
        if !self.substep()||!self.substep(){return false;}
        self.time+=1;
        true
    }
}

#[no_mangle]
pub extern "C" fn solver_create(w: u32,h: u32,speed: f64,viscosity: f64)->*mut Solver {
    match Solver::new(w as usize,h as usize,speed,viscosity){
        Some(s)=>Box::into_raw(Box::new(s)),
        None=>std::ptr::null_mut(),
    }
}
#[no_mangle]
pub unsafe extern "C" fn solver_free(p:*mut Solver){
    if !p.is_null(){drop(Box::from_raw(p));}
}
#[no_mangle]
pub unsafe extern "C" fn solver_solid_ptr(p:*mut Solver)->*mut u8{
    if p.is_null(){return std::ptr::null_mut();}
    (*p).solid.as_mut_ptr()
}
#[no_mangle]
pub unsafe extern "C" fn solver_reset(p:*mut Solver)->i32{
    if p.is_null(){return 0;}
    (*p).reset();1
}
#[no_mangle]
pub unsafe extern "C" fn solver_step_many(p:*mut Solver,steps:u32)->i32{
    if p.is_null()||steps>10000{return -1;}
    let s=&mut *p;
    for _ in 0..steps {if !s.step(){return -1;}}
    steps as i32
}
#[no_mangle]
pub unsafe extern "C" fn solver_rho_ptr(p:*mut Solver)->*const f64{
    if p.is_null(){return std::ptr::null();}
    (*p).rho.as_ptr()
}
#[no_mangle]
pub unsafe extern "C" fn solver_ux_ptr(p:*mut Solver)->*const f64{
    if p.is_null(){return std::ptr::null();}
    (*p).ux.as_ptr()
}
#[no_mangle]
pub unsafe extern "C" fn solver_uy_ptr(p:*mut Solver)->*const f64{
    if p.is_null(){return std::ptr::null();}
    (*p).uy.as_ptr()
}
#[no_mangle]
pub unsafe extern "C" fn solver_time(p:*const Solver)->u32{
    if p.is_null(){return 0;}(*p).time as u32
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]fn solver_is_stable_and_reproducible(){
        let mut a=Solver::new(48,28,0.085,0.025).unwrap();
        let mut b=Solver::new(48,28,0.085,0.025).unwrap();
        for y in 9..19 {for x in 12..18{a.solid[x+y*48]=1;b.solid[x+y*48]=1;}}
        a.reset();b.reset();
        for _ in 0..12{assert!(a.step());assert!(b.step());}
        assert_eq!(a.time,12);
        assert_eq!(a.ux,b.ux);
        assert!(a.rho.iter().all(|v|v.is_finite()));
    }
}
